= Учет налогового вычета ИИС в доходности счета

Investbook позволяет учитывать доходность ИИС с учетом налоговых вычетов. Если вы пользуетесь вычетом типа В, то
ничего делать не нужно: брокер не удерживает налог с курсовой разницы купли-продажи бумаг, поэтому таблица
<<cash-flow.adoc#, "Доходноcть портфеля">> отобразит корректную доходность.

Если вы пользуетесь вычетом типа А, то вы должны ежегодно подавать декларацию 3-НДФЛ с указанием информации по ИИС.
Налоговая по итогу проверки переведет на ваш банковский счет вычет. С точки зрения доходности ИИС налоговый вычет можно
расценивать как дополнительный доход, который сгенерирован счетом ИИС и выведен на банковский счет. Для учета вычета,
воспользуйтесь Формами (раздел "События по счетам", действие http://localhost/events/edit-form["Добавить"]). Выберите
в поле "Операция" значение "Вычет ИИС тип А", укажите дату, номер счета и полученную на банковский счет сумму. Поле
"Описание" будет заполнено автоматически (если будете его редактировать, то оставьте слова "вычет" и "ИИС" - это
слова-маркеры для Investbook). Операция будет сохранена как доход, который выведен со счета ИИС на банковский счет.
В аналитическом отчете Investbook вы увидите операцию на вкладке <<cash-flow.adoc#, "Доходноcть портфеля">>, на этой же
вкладке будет указана годовая доходность с учетом налогового вычета.
