== Рекомендации по загрузке брокерских отчетов
. <<tinkoff.adoc#,Тинькофф>>
. <<sber.adoc#,Сбербанк>>
. <<vtb.adoc#,ВТБ Брокер>>
. <<psb.adoc#,Промсвязьбанк Брокер>>
. <<uralsib.adoc#,Уралсиб Брокер>>

Загрузка отчетов остальных брокеров не содержит специальных рекомендаций (если вы используете стороннее расширение
для поддержки дополнительных брокеров, обратитесь за рекомендациями к разработчику расширения).

По всем брокерам старайтесь загружать отчеты так часто, насколько детализировано вам необходимо строить график
изменения активов. Каждый отчет брокера формирует на графике (<<portfolio-analysis.adoc#,роста активов>>) одну точку.
Этот алгоритм касается только графика роста активов. Сделки дивиденды, купоны, налоги, комиссии и т.д. учитываются все,
даже если загружать отчеты раз в год (последний загружаемый отчет должен охватить период, который не вошел
в предыдущий загруженный отчет; допустимо перекрытие отчетов по времени - дублей не будет).

== Ручное внесение сделок
. С использованием <<investbook-forms.adoc#,Форм>>
. С использованием <<investbook-input-format.adoc#,excel или csv>> файла
. С использованием <<investbook-api.adoc#,API>> приложения

== Описание отчета Investbook
<<investbook-report.adoc#,Описание отчета Investbook>>

== Учет налогов
<<taxes-doc.adoc#,Документация по учету налогов>>

== Решение проблем
. Бэкап и восстановление link:/portfolio-open-format/index.html[данных]
. Самостоятельное <<troubleshooting.adoc#,исправление проблем>>
. Обратиться за помощью в https://t.me/+zriyX7tRQOc0MDEy[техническую поддержку]

=== Контакты
- Телеграм чат https://t.me/+zriyX7tRQOc0MDEy[технической поддержки];
- Обсуждение на форуме https://www.banki.ru/forum/?PAGE_NAME=read&FID=21&TID=380178[banki.ru];
- Страница приложения на https://smart-lab.ru/trading-software/Investbook[smart-lab.ru] и
  https://smart-lab.ru/profile/SpaciousTeam[страница для связи];
- e-mail: mailto:spacious-team@ya.ru[spacious-team@ya.ru]

== Тонкая настройка
. <<configuration.adoc#,Настройка приложения>>
. <<dbms-changing.adoc#,Смена СУБД>>
