= Формат Investbook

Позволяет из excel (xls, xlsx) или csv файла внести в Investbook информацию:

- о сделках (акции, ETF, облигации, срочные инструменты и валюта);
- о событиях по инструментам (получение дивиденда, купона, амортизации и погашение облигации, зачисление и списание
  вариационной маржи, удержании налога);
- о событиях по счету (внесение, вывод денежных средств, налоги, вычеты, комиссии брокера за обслуживание и т.д.);
- об оценке стоимости портфеля и остатках денежных средств;
- о событиях с депозитарным счетом (зачисление, списание бумаг, в т.ч в результате сплитов и конвертации акций).

Способ можно использовать, если отчет Вашего брокер еще не поддерживается. Является альтернативой ручному внесению
сделок через <<investbook-forms.adoc#,Формы>>. Для загрузки файла нужно перейти с главной страницы по ссылке
"Загрузить отчеты брокера". Имя загружаемого excel (xls, xlsx) и csv файла может быть любым.

Шаблоны файлов:

. Пример link:/investbook-format-example.xlsx[excel] файла
. Пример link:/investbook-format-example.csv[csv] файла

Форматы excel/csv взаимозаменяемы: можно редактировать excel файл, сохранить в csv формат и загрузить csv (или наоборот:
редактировать csv, сохранить как xls/xlsx файл и загрузить).

После успешной загрузки файл резервно сохранится в домашней директории пользователя в папке
`investbook\report-backups\Investbook`.

