== Ошибка "Failed to launch JVM"

Если при запуске приложения возникает такая ошибка, значит приложение уже работает (возможно предыдущий запуск еще
не успел открыть окно браузера или вы сами закрыли вкладку браузера).

. Попробуйте запустить браузер по адресу http://localhost
. Если предыдущий пункт не помог запустите диспетчер задач и удалите процесс `Investbook.exe`, после этого повторно
  запустите приложение через ярлык.
. Если предыдущий пункт не помог, значит имеет ошибка в работе приложения, которая указана в логе. Лог можно найти
  в домашней директории пользователя в файле `investbook\investbook.log`. Изучите ошибку и исправьте ee самостоятельно
  или обратитесь с ней к https://t.me/investbook_support[разработчикам] приложения. Однин из вариантов самостоятельного
  решения проблемы описан <<delete-db, ниже>>.

== Запускается окно браузера с ошибкой

Для Chrome это может быть, например, ошибка `ERR_CONNECTION_REFUSED`. Это означает, что имеет ошибка в работе
приложения, которая указана в логе. Лог можно найти в домашней директории пользователя в файле
`investbook\investbook.log`. Изучите ошибку и исправьте ee самостоятельно или обратитесь с ней к
https://t.me/investbook_support[разработчикам] приложения. Однин из вариантов самостоятельного решения проблемы описан
<<delete-db, ниже>>.

[[delete-db]]
== Удаление БД

Если приложение не запускается, попробуйте удалить в домашней папке пользователя файлы БД `investbook\investbook.mv.db`
и `investbook\investbook.trace.db`. Остановите процесс `Investbook.exe` через Диспетчер задач и повторно запустите
приложение через ярлык. Если приложение запустилось, загрузите бекапы отчетов брокера из домашней директории
пользователя из папки `investbook\report-backups`.