== Открывается пустая страница в браузере

Рекомендуется использовать Mozilla Firefox, Google Chrome и Safari. Совместимость с другими браузерами не тестируется.
Известно о проблемах с Internet Explorer.

== Ошибка "Failed to launch JVM"

Если при запуске приложения возникает такая ошибка, значит приложение уже работает (возможно предыдущий запуск еще
не успел открыть окно браузера или вы сами закрыли вкладку браузера).

. Попробуйте запустить браузер по адресу http://localhost
. Если предыдущий пункт не помог, запустите диспетчер задач и удалите процесс `Investbook.exe`, после этого повторно
  запустите приложение через ярлык.
. Если предыдущий пункт не помог, значит имеется ошибка в работе приложения, которая указана в логе. Лог можно найти
  в домашней директории пользователя в файле `investbook\investbook.log`. Изучите ошибку и исправьте ee самостоятельно
  или обратитесь с ней в https://t.me/investbook_support[техническую поддержку]. Один из вариантов
  самостоятельного решения проблемы описан в разделе "<<delete-db, Исправление ошибок через повторную загрузку отчетов>>".

== Ошибка в логе "Port 80 was already in use"

Лог расположен в домашней папке пользователя в подпапке `investbook`, файл `investbook.log`. Для исправления ошибки
в папке, в которую установлено Приложение (по умолчанию на Windows устанавливается в `C:\Program Files\Investbook`),
откройте папку `app` и измените в файле `application-conf.properties` неиспользуемый порт, например попробуйте 8080
[source, properties]
----
server.port = 8080
----
Повторно запустите приложение и откройте в браузере http://localhost:8080 Если ошибка осталась та же, измените порт
на другой в диапазоне 1000 - 65535.

== Запускается окно браузера с ошибкой

Для Chrome это может быть, например, ошибка `ERR_CONNECTION_REFUSED`, а для Mozilla Firefox -
"Попытка соединения не удалась". Это означает, что имеется ошибка в работе приложения, которая указана в логе. Лог можно
найти в домашней директории пользователя в файле `investbook\investbook.log`. Изучите ошибку и исправьте ee
самостоятельно или обратитесь с ней в https://t.me/investbook_support[техническую поддержку]. Один из вариантов
самостоятельного решения проблемы описан в разделе "<<delete-db, Исправление ошибок через повторную загрузку отчетов>>".

[[delete-db]]
== Исправление ошибок через повторную загрузку отчетов

Если приложение не запускается или не выгружается отчет, возможно данные загружены старой версией Приложения.
Ошибка может быть в некоторых случаях исправлена, если загрузить данные из актуальной версии Приложения.

WARNING: Внимание: этот способ сохраняет все данные, загруженные из отчета, но теряет данные
внесенные вручную через "Формы".

. Остановите процесс `Investbook.exe` с главной страницы сайта или через Диспетчер задач.
. https://github.com/spacious-team/investbook/releases/latest[Скачайте] свежую версию приложения.
. Удалите в домашней папке пользователя файлы БД `investbook\investbook.mv.db` и `investbook\investbook.trace.db`.
. Запустите приложение через ярлык.
. Загрузите бекапы отчетов брокера из домашней директории пользователя из папки `investbook\report-backups`.

Если проблема по-прежнему сохраняется, обратитесь в https://t.me/investbook_support[техническую поддержку].