= ВТБ Брокер

Запросите отчет брокера со страницы https://lk.olb.ru -> вкладка "Отчеты" -> меню "Брокерский отчет" с даты,
на который оканчивался предыдущий запрошенный отчет по самую свежую дату. Если отчет не загружался в `Investbook`,
то запросите брокерский отчет за весь период. А потом подгружайте новые отчеты с последней запрошенной даты.
Если не указываете брокера из выпадающего списка на странице загрузки отчета, то для определения брокера
имя файла должно соответствовать шаблону `XXXXXXXX_yyyyMMdd_yyyyMMdd_NNNNNNN.xls`.

По срочному рынку в отчете ВТБ ежедневные зачисления вариационной маржи указываются без привязки к контракту. Если
в течение дня было открыто несколько типов контрактов (например BR-6.22 и Si-6.22), то нельзя сказать сколько какой
из контрактов принес прибыли. Investbook хранит ежедневную вариационную маржу с привязкой к контракту, поэтому из таких
отчетов вариационная маржа не может быть корректно извлечена и сохранена. Если же в таблице отчета ВТБ "Открытые позиции
по Производным финансовым инструментам" указан только один контракт, то ежедневная вариационная маржа может быть
привязана к конкретному контракту. В таком случае она парсится и сохраняется в Investbook.
